Update patch set 7
Patch Set 7:

> Hm, I'm not able to get the tests running, but I see a different
 > error, stack trace below.
 > 
 > I do have a build change to merge these two jars, respecting
 > META-INF/services, will mail that momentarily and you can try it
 > out.
 > 
 > FAIL    CACHED  0 Passed   0 Skipped   1 Failed   com.googlesource.gerrit.plugins.eventslog.SomeIT
 > FAILURE someTest: /usr/local/google/home/dborowitz/nobackup/d/events-log/buck-out/gen/events-log.jar
 > java.nio.file.NoSuchFileException: /usr/local/google/home/dborowitz/nobackup/d/events-log/buck-out/gen/events-log.jar
 > at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
 > at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
 > at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
 > at sun.nio.fs.UnixCopyFile.copy(UnixCopyFile.java:526)
 > at sun.nio.fs.UnixFileSystemProvider.copy(UnixFileSystemProvider.java:253)
 > at java.nio.file.Files.copy(Files.java:1274)
 > at com.google.gerrit.acceptance.PluginDaemonTest.copyJarToTestSite(PluginDaemonTest.java:212)
 > at com.google.gerrit.acceptance.PluginDaemonTest.deployPlugin(PluginDaemonTest.java:92)
 > at com.google.gerrit.acceptance.PluginDaemonTest.beforeTest(PluginDaemonTest.java:57)
 > at com.google.gerrit.acceptance.AbstractDaemonTest$1$1.evaluate(AbstractDaemonTest.java:174)
 > at org.junit.rules.RunRules.evaluate(RunRules.java:20)
 > at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
 > at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
 > at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
 > at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
 > at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
 > at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
 > at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
 > at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
 > at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
 > at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
 > at org.junit.runners.Suite.runChild(Suite.java:127)
 > at org.junit.runners.Suite.runChild(Suite.java:26)
 > at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
 > at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
 > at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
 > at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
 > at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
 > at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
 > at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
 > at org.junit.runners.Suite.runChild(Suite.java:127)
 > at org.junit.runners.Suite.runChild(Suite.java:26)
 > at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
 > at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
 > at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
 > at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
 > at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
 > at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
 > at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
 > at org.junit.runner.JUnitCore.run(JUnitCore.java:138)
 > at com.facebook.buck.junit.JUnitRunner.run(JUnitRunner.java:104)
 > at com.facebook.buck.junit.BaseRunner.runAndExit(BaseRunner.java:210)
 > at com.facebook.buck.junit.JUnitMain.main(JUnitMain.java:47)
 > at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 > at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
 > at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 > at java.lang.reflect.Method.invoke(Method.java:483)
 > at com.facebook.buck.java.runner.FileClassPathRunner.main(FileClassPathRunner.java:87)

Strange; I understand the exception but not how it could happen in your case. Likely your FS env differing from ours in a way that breaks the code unexpectedly. Would this patch set -[1]- be an attempt at fixing that exception case? (Pushed on top of ongoing Drafts.) -Btw, thx for the fix[2] for this overall issue we've been discussing!

[1] https://gerrit-review.googlesource.com/#/c/69425/14
[2] https://gerrit-review.googlesource.com/#/c/69850/

Patch-set: 7