Update patch set 4
Patch Set 4: Code-Review-1

I tried this patch, but it did not work.  The upgrade no longer fails but I could not start gerrit after an upgrade from gerrit ver 2.4.2.  I get a guice provision error..

[2014-01-12 10:05:08,587] INFO  com.google.gerrit.server.cache.h2.H2CacheFactory : Enabling disk$
[2014-01-12 10:05:10,550] WARN  com.google.gerrit.sshd.SshDaemon : Disabling cipher aes192-cbc: $
[2014-01-12 10:05:10,551] WARN  com.google.gerrit.sshd.SshDaemon : Disabling cipher aes256-cbc: $
[2014-01-12 10:05:10,588] WARN  com.google.gerrit.httpd.GitWebConfig : gitweb not installed (no $
[2014-01-12 10:05:11,729] INFO  com.google.gerrit.server.git.LocalDiskRepositoryManager : Defaul$
[2014-01-12 10:05:11,763] INFO  com.google.gerrit.server.plugins.PluginLoader : Loading plugins $
[2014-01-12 10:05:11,765] ERROR com.google.gerrit.pgm.Daemon : Unable to start daemon
com.google.inject.ProvisionException: Guice provision errors:

1) No index versions ready; run Reindex

1 error
        at com.google.gerrit.lucene.LuceneVersionManager.start(LuceneVersionManager.java:118)
        at com.google.gerrit.lifecycle.LifecycleManager.start(LifecycleManager.java:74)
        at com.google.gerrit.pgm.Daemon.start(Daemon.java:285)
        at com.google.gerrit.pgm.Daemon.run(Daemon.java:197)
        at com.google.gerrit.pgm.util.AbstractProgram.main(AbstractProgram.java:63)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at com.google.gerrit.launcher.GerritLauncher.invokeProgram(GerritLauncher.java:169)
        at com.google.gerrit.launcher.GerritLauncher.mainImpl(GerritLauncher.java:96)
        at com.google.gerrit.launcher.GerritLauncher.main(GerritLauncher.java:53)
        at Main.main(Main.java:25)

Patch-set: 4