Update patch set 3
Patch Set 3:

> > Not sure why it is failing.
 > 
 > Same problem as before - you're using the inline editor instead of
 > building locally.
 > 
 > error: cannot find symbol linksPanel.addStyleName(style.parentWebLink());
Hi I test this locally when I am near a computer.

But as I am not very good in the java language yet I publish the patches through inline edit since I doint know how to add this functionality in java.

Patch-set: 3
Reviewer: Gerrit User 1029953 <1029953@173816e5-2b9a-37c3-8a2e-48639d4f1153>
Label: Verified=0