Update patch set 1
Patch Set 1: Verified-1

Missing an exported dep somehow:

 /usr/local/google/home/dborowitz/nobackup/d/gerrit-workdirs/gerrit2/gerrit-server/src/test/java/com/google/gerrit/rules/PrologTestCase.java:60: error: cannot access com.google.gerrit.extensions.config.FactoryModule
     moduleList.add(new PrologModule.EnvironmentModule());
               ^
   class file for com.google.gerrit.extensions.config.FactoryModule not found
 Errors: 1. Warnings: 1.
 BUILD FAILED: //gerrit-server:prolog_test_case failed with exit code 1:
 javac
 gerrit-server/BUCK (:prolog_test_case) is missing deps:
     '//gerrit-extension-api:api',

Patch-set: 1
Label: Verified=-1