Update patch set 3
Patch Set 3:

anyway here more test results from jetty, tomcat and wlp in different modes just for the record: 

1.) jetty

a.) unpacked war/directory:
URL: "jar:file:/home/thomas/gerrit/war-unpacked/WEB-INF/lib/gerrit-launcher-launcher.jar!/com/google/gerrit/launcher/GerritLauncher.class"
works.

b.) war file:
URL: "jar:file:/tmp/jetty-0.0.0.0-9080-gerrit.war-_gerrit-any-2652422072818152395.dir/webapp/WEB-INF/lib/gerrit-launcher-launcher.jar!/com/google/gerrit/launcher/GerritLauncher.class"
works.

c.) war file with <Set name="extractWAR">false</Set>
Startup fails in Jetty (jetty-distribution-9.3.8.v20160314) with
java.lang.NullPointerException: no !/ in spec
	at sun.net.www.protocol.jar.Handler.parseAbsoluteSpec(Handler.java:171)
	at sun.net.www.protocol.jar.Handler.parseURL(Handler.java:151)
	at java.net.URL.<init>(URL.java:622)
	at java.net.URL.<init>(URL.java:490)
	at java.net.URL.<init>(URL.java:439)
	at java.net.JarURLConnection.parseSpecs(JarURLConnection.java:175)
	at java.net.JarURLConnection.<init>(JarURLConnection.java:158)
	at sun.net.www.protocol.jar.JarURLConnection.<init>(JarURLConnection.java:81)
	at sun.net.www.protocol.jar.Handler.openConnection(Handler.java:41)
	at java.net.URL.openConnection(URL.java:979)
	at org.eclipse.jetty.webapp.MetaInfConfiguration.getTlds(MetaInfConfiguration.java:406)
	at org.eclipse.jetty.webapp.MetaInfConfiguration.scanForTlds(MetaInfConfiguration.java:326)
	at org.eclipse.jetty.webapp.MetaInfConfiguration.scanJars(MetaInfConfiguration.java:143)
	at org.eclipse.jetty.webapp.MetaInfConfiguration.preConfigure(MetaInfConfiguration.java:94)
	at org.eclipse.jetty.webapp.WebAppContext.preConfigure(WebAppContext.java:480)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:516)

this seems to be a limitation in jetty 9.3. see also https://github.com/eclipse/jetty.project/issues/455

2.) wlp-1.0.12 (8.5.5.9)

a.) unpacked war/directory:
URL=wsjar:file:/home/thomas/gerrit/war-unpacked/WEB-INF/lib/gerrit-launcher-launcher.jar!/com/google/gerrit/launcher/GerritLauncher.class
works

b.) war file:
URL=wsjar:file:/home/thomas/wlp/usr/servers/defaultServer/workarea/org.eclipse.osgi/58/data/cache/com.ibm.ws.app.manager_28/.cache/WEB-INF/lib/gerrit-launcher-launcher.jar!/com/google/gerrit/launcher/GerritLauncher.class

doens't work because e.g. DirectoryGwtUiServlet (which is basically the ResourecServlet) uses above file system path, but WLP just uses above as cache directory for classes and doesn't extract all WAR content their. The gerrit_ui directory exits but is empty.

3.) tomcat 8.0.35

a.) unpacked war/directory:
jar:file:/home/thomas/gerrit/war-unpacked/WEB-INF/lib/gerrit-launcher-launcher.jar!/com/google/gerrit/launcher/GerritLauncher.class
works

b.) war file with unpackWAR="true"
jar:file:/home/thomas/tomcat-base/webapps/gerrit/WEB-INF/lib/gerrit-launcher-launcher.jar!/com/google/gerrit/launcher/GerritLauncher.class
works

c.) war file with unpackWAR="false"
jar:war:file:/home/thomas/gerrit/war/gerrit.war*/WEB-INF/lib/gerrit-launcher-launcher.jar!/com/google/gerrit/launcher/GerritLauncher.class
doesn't work.

I think the patch extracts the file path as /home/thomas/gerrit/war/gerrit.war*/WEB-INF/lib/gerrit-launcher-launcher.jar which is wrong.

anyway even if above logic would extract the correct file path to the war /home/thomas/gerrit/war/gerrit.war I think it still won't work as the StaticModule falls back to WarGwtUiServlet which also uses file system operations to try to get the resource which never can work in an war file, possbily mounted read-only. I think the correct way would be to use ServletContext.getResourceAsStream() method or fallback to the classloader to fetch the resources if possible.
searching the internet for tomcat and unpackWAR="false" results in many bug reports saying that this or that framework doesn't work correctly in this mode. their is even an discussion of the tomcat developers if it's still worth to support this mode...

Patch-set: 3