Update patch set 1
Patch Set 1:

Interesting that your change broke an unrelated Integration test:
There was 1 failure:
1) killTaskTests_inOrder(com.google.gerrit.acceptance.rest.config.KillTaskIT)
java.lang.AssertionError: Not true that <[com.google.gerrit.server.config.ListTasks$TaskInfo@748015f8]> has a size of <2>. It is <1>
	at com.google.gerrit.acceptance.rest.config.KillTaskIT.killTask(KillTaskIT.java:46)
	at com.google.gerrit.acceptance.rest.config.KillTaskIT.killTaskTests_inOrder(KillTaskIT.java:65)

Shall we flag KillTaskIT as Flaky?

Patch-set: 1