Update patch set 3
Patch Set 3: Code-Review+1

Looks good to me. The test succeeds if I run it from Eclipse but I'm unable to verify the test from the command line. Running it from the command line results in various errors [1,2,3]. I'm not sure why I'm seeing these errors and it could be caused by my local setup.

[1]

 $ buck clean
 $ buck test //gerrit-acceptance-tests/src/test/java/com/google/gerrit/acceptance/server/project:LabelTypeIT
 [-] PARSING BUILD FILES...FINISHED 1.1s
 [-] BUILDING...FINISHED 1.6s
 Log:
 TESTING //gerrit-acceptance-tests/src/test/java/com/google/gerrit/acceptance/server/project:LabelTypeIT
 FAIL  97.5s  9 Passed   1 Failed   com.google.gerrit.acceptance.server.project.LabelTypeIT
 FAILURE noCopyMaxScoreOnRework: Java heap space
 java.lang.OutOfMemoryError: Java heap space
 ...
 TESTS FAILED: 1 Failures

[2]

 $ buck clean
 $ buck test //gerrit-acceptance-tests/src/test/java/com/google/gerrit/acceptance/server/project:LabelTypeIT
 [-] PARSING BUILD FILES...FINISHED 1.1s
 [-] BUILDING...FINISHED 1.6s
 Log:
 TESTING //gerrit-acceptance-tests/src/test/java/com/google/gerrit/acceptance/server/project:LabelTypeIT
 FAIL  32.5s  9 Passed   1 Failed   com.google.gerrit.acceptance.server.project.LabelTypeIT
 FAILURE ngSegment.getOrCompute: ect.internal.guava.collect.$ComputingConcurrentHashMap
 com.google.inject.internal.guava.collect.$ComputationException: java.lang.OutOfMemoryError: GC overhead limit exceeded
 ...
 TESTS FAILED: 1 Failures

[3]

 $ buck clean
 $ buck test //gerrit-acceptance-tests/src/test/java/com/google/gerrit/acceptance/server/project:LabelTypeIT
 [-] PARSING BUILD FILES...FINISHED 1.1s
 [-] BUILDING...FINISHED 1.6s
 Log:
 TESTING //gerrit-acceptance-tests/src/test/java/com/google/gerrit/acceptance/server/project:LabelTypeIT
 ... and now it hangs ...

Patch-set: 3
Label: Code-Review=+1