Update patch set 3
Patch Set 3:

This breaks //gerrit-gwtui:ui_dbg.

com.google.inject.CreationException: Guice creation errors:  1) No implementation for com.google.gerrit.server.util.RequestScopePropagator was bound.
...

Patch-set: 3
Reviewer: Gerrit User 1012687 <1012687@173816e5-2b9a-37c3-8a2e-48639d4f1153>
Label: Verified=0