Update patch set 1
Patch Set 1:

When running `buck test` with this change and up-to-date submodules I run into buck test
Not using buckd because watchman isn't installed.
[+] PARSING BUCK FILES...0.8s
Traceback (most recent call last):
  File "/usr/local/google/home/sbeller/OSS/gerrit/buck-out/tmp/buck_run.jdr4bi/buck118906653725927236.py", line 1324, in <module>
    main()
  File "/usr/local/google/home/sbeller/OSS/gerrit/buck-out/tmp/buck_run.jdr4bi/buck118906653725927236.py", line 478, in main
    values = buildFileProcessor.process(build_file.rstrip())
  File "/usr/local/google/home/sbeller/OSS/gerrit/buck-out/tmp/buck_run.jdr4bi/buck118906653725927236.py", line 406, in process
    implicit_includes=self._implicit_includes)
  File "/usr/local/google/home/sbeller/OSS/gerrit/buck-out/tmp/buck_run.jdr4bi/buck118906653725927236.py", line 397, in _process_build_file
    implicit_includes=implicit_includes)
  File "/usr/local/google/home/sbeller/OSS/gerrit/buck-out/tmp/buck_run.jdr4bi/buck118906653725927236.py", line 361, in _process
    exec(code, module.__dict__)
  File "/usr/local/google/home/sbeller/OSS/gerrit/gerrit-plugin-gwt-archetype/src/main/resources/archetype-resources/BUCK", line 14, in <module>
    'Gerrit-HttpModule: ${package}.HttpModule',
  File "/usr/local/google/home/sbeller/OSS/gerrit/tools/default.defs", line 134, in gerrit_plugin
    mf_cmd = 'v=%s;' % git_describe(name)
  File "/usr/local/google/home/sbeller/OSS/gerrit/tools/git.defs", line 21, in git_describe
    p = subprocess.Popen(cmd, stdout = subprocess.PIPE, cwd = 'plugins/%s' % plugin)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory: 'plugins/${pluginName}'
[2015-04-14 10:11:40.406][error][command:22c628bc-2c55-4f40-be40-739893362064][tid:01][com.facebook.buck.json.ProjectBuildFileParser] Process java.lang.UNIXProcess@33fe5528 exited with error code 1
BUILD FAILED: Parse error for build file /usr/local/google/home/sbeller/OSS/gerrit/gerrit-plugin-gwt-archetype/src/main/resources/archetype-resources/BUCK: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was END_DOCUMENT at line 1 column 145933


I have no idea how this is related to this change, though that error doesn't surface when testing origin/master

Patch-set: 1