Update patch set 2
Patch Set 2:

This is producing NPEs server-side and 500s for the client. For example, when I try to load this change:

 Error in GET /changes/90018/detail?O=10004
 com.google.gwtorm.server.OrmException: java.lang.NullPointerException
	at com.google.gerrit.server.change.ChangeJson.format(ChangeJson.java:303)
	at com.google.gerrit.server.change.ChangeJson.format(ChangeJson.java:285)
	at com.google.gerrit.server.change.ChangeJson.format(ChangeJson.java:263)
	at com.google.gerrit.server.change.GetChange.apply(GetChange.java:50)
	at com.google.gerrit.server.change.GetDetail.apply(GetDetail.java:51)
	at com.google.gerrit.server.change.GetDetail.apply(GetDetail.java:26)
	at com.google.gerrit.httpd.restapi.RestApiServlet.service(RestApiServlet.java:367)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
[...]
 Caused by: java.lang.NullPointerException
	at com.google.gerrit.server.change.ChangeJson.setLabelScores(ChangeJson.java:670)
	at com.google.gerrit.server.change.ChangeJson.labelsForClosedChange(ChangeJson.java:845)
	at com.google.gerrit.server.change.ChangeJson.labelsFor(ChangeJson.java:598)
	at com.google.gerrit.server.change.ChangeJson.toChangeInfo(ChangeJson.java:499)
	at com.google.gerrit.server.change.ChangeJson.format(ChangeJson.java:294)
	... 105 more

Patch-set: 2