Update patch set 6
Patch Set 6: Verified-1

$ buck test --all

fails with:

/Users/d038025/dev/gerrit/gerrit-acceptance-tests/src/test/java/com/google/gerrit/acceptance/git/AbstractPushForReview.java:18: error: package com.google.gerrit.acceptance.rest.change does not exist
...
gerrit-acceptance-tests/src/test/java/com/google/gerrit/acceptance/git/BUCK (:push_for_review) is missing deps:
    '//gerrit-acceptance-tests/src/test/java/com/google/gerrit/acceptance/rest/change:HashtagsIT',

Patch-set: 6
Reviewer: Gerrit User 1003873 <1003873@173816e5-2b9a-37c3-8a2e-48639d4f1153>
Label: Verified=-1