Update patch set 6
Patch Set 6:

> > error: package com.google.gerrit.acceptance.rest.change does not
 > > exist
 > > ...
 > 
 > This is because I've introduced a dependency.  Didn't see this
 > error because I was only testing it with JUnit in Eclipse :(

Yeah, kind of dangerous, because Eclipe is seeing combined classpath from all Gerrit projects.

Patch-set: 6
Label: Verified=0