Update patch set 3
Patch Set 3:

I get: 

[2015-06-12 11:03:35,886] ERROR com.google.gerrit.pgm.http.jetty.HiddenErrorHandler : Error in GET /plugins/gitiles/NewTest/+/de9eaba311c7ac73d69d20029c6671dcd11fb2fa
java.lang.RuntimeException: Error creating extended parser class: use Optional.orNull() instead of Optional.or(null)
        at org.parboiled.Parboiled.createParser(Parboiled.java:75)
        at org.pegdown.plugins.PegDownPlugins$Builder.withPlugin(PegDownPlugins.java:113)
        at com.google.gitiles.doc.GitilesMarkdown.newParser(GitilesMarkdown.java:73)
        at com.google.gitiles.doc.GitilesMarkdown.parseFile(GitilesMarkdown.java:58)
        at com.google.gitiles.ReadmeHelper.render(ReadmeHelper.java:95)
        at com.google.gitiles.TreeSoyData.toSoyData(TreeSoyData.java:156)
        at com.google.gitiles.TreeSoyData.toSoyData(TreeSoyData.java:166)
        at com.google.gitiles.RevisionServlet.doGetHtml(RevisionServlet.java:104)
        at com.google.gitiles.BaseServlet.doGet(BaseServlet.java:117)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:618)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:725)
        at com.google.gitiles.GitilesFilter$DispatchFilter$1.doFilter(GitilesFilter.java:154)
        at com.googlesource.gerrit.plugins.gitiles.MenuFilter.doFilter(MenuFilter.java:63)
        at com.google.gitiles.GitilesFilter$DispatchFilter$1.doFilter(GitilesFilter.java:152)
        at com.google.gitiles.GitilesFilter$DispatchFilter.doFilter(GitilesFilter.java:147)
        at com.google.gitiles.AbstractHttpFilter.doFilter(AbstractHttpFilter.java:32)
        at org.eclipse.jgit.http.server.glue.UrlPipeline$Chain.doFilter(UrlPipeline.java:235)
        at com.google.gitiles.ViewFilter.doFilter(ViewFilter.java:122)
        at com.google.gitiles.AbstractHttpFilter.doFilter(AbstractHttpFilter.java:32)
        at com.google.gitiles.ViewFilter.doFilter(ViewFilter.java:38)
        at org.eclipse.jgit.http.server.glue.UrlPipeline$Chain.doFilter(UrlPipeline.java:235)
        at org.eclipse.jgit.http.server.RepositoryFilter.doFilter(RepositoryFilter.java:151)
...

Caused by: java.lang.NullPointerException: use Optional.orNull() instead of Optional.or(null)
        at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:226)
        at com.google.common.base.Absent.or(Absent.java:51)
        at org.parboiled.transform.ClassNodeInitializer.getInputStream(ClassNodeInitializer.java:225)
        at org.parboiled.transform.ClassNodeInitializer.process(ClassNodeInitializer.java:93)
        at org.parboiled.transform.ParserTransformer.extendParserClass(ParserTransformer.java:97)
        at org.parboiled.transform.ParserTransformer.transformParser(ParserTransformer.java:66)
        at org.parboiled.Parboiled.createParser(Parboiled.java:67)

with this patch and gitiles-plugin (with guice patch) build against gitiles-master (locally build), as other wise gitiles throws on the auto-closable changes...

But thanks for tackling this

Patch-set: 3