Update patch set 2
Patch Set 2: Verified-1

Patchset merges but does not build.
The following snippet of output may point you in the right direction:

  Not using buckd because watchman isn't installed.
[-] PARSING BUCK FILES...FINISHED 2.5s
/home/deckard/workspace/gerrit/gerrit-gwtui/src/main/java/com/google/gerrit/client/change/ChangeScreen2.java:389: error: incomparable types: java.lang.String and int
    if (currentlyViewedPatchSet != currentPatchSet) {
                                ^
Errors: 1. Warnings: 0.
BUILD FAILED: //gerrit-gwtui:ui_module failed with exit code 1:
javac
[-] BUILDING...FINISHED 32.3s
:

Patch-set: 2
Label: Verified=-1