Update patch set 4
Patch Set 4: Verified-1

Patchset merges but does not build.
The following snippet of output may point you in the right direction:

  Not using buckd because watchman isn't installed.
[-] PARSING BUCK FILES...FINISHED 3.8s
/home/deckard/workspace/gerrit/gerrit-server/src/main/java/com/google/gerrit/server/git/MergeOp.java:853: error: ';' expected
        subOp.updateSubmoduleSubscriptions(destBranch)
                                                      ^
Errors: 1. Warnings: 0.
BUILD FAILED: //gerrit-server:server failed with exit code 1:
javac
[-] BUILDING...FINISHED 5.9s
:

Patch-set: 4
Label: Verified=-1