Update patch set 3
Patch Set 3: -Code-Review Verified-1

The generated .war file seems to be missing some parts:

 $ java -jar ./buck-out/gen/headless.war init -d ~/gerrit_testsite
 Error: Invalid or corrupt jarfile ./buck-out/gen/headless.war

I did a `jar -tf` on the .war file and it's missing the `META-INF/MANIFEST.MF` file.

http://paste.openstack.org/show/185858/

Patch-set: 3
Label: Verified=-1