Update patch set 7
Patch Set 7:

I get the error locally on docker using ci docker image

jenkins@ec4d381ac7c1:/gerrit$ bash ./polygerrit-ui/app/run_test.sh
WARNING: Sandboxed execution is not supported on your system and thus hermeticity of actions cannot be guaranteed. See http://bazel.build/docs/bazel-user-manual.html#sandboxing for more information. You can turn off this warning via --ignore_unsupported_sandboxing.
INFO: Found 1 test target...
FAIL: //polygerrit-ui/app:wct_test (see /home/jenkins/.cache/bazel/_bazel_jenkins/4198cff55ec080b15cc0805ba32b9d92/execroot/gerrit/bazel-out/local-fastbuild/testlogs/polygerrit-ui/app/wct_test/test.log).
Target //polygerrit-ui/app:wct_test up-to-date:
  bazel-bin/polygerrit-ui/app/wct_test
INFO: Elapsed time: 0.963s, Critical Path: 0.74s
//polygerrit-ui/app:wct_test                                             FAILED in 1 out of 2 in 0.7s
  /home/jenkins/.cache/bazel/_bazel_jenkins/4198cff55ec080b15cc0805ba32b9d92/execroot/gerrit/bazel-out/local-fastbuild/testlogs/polygerrit-ui/app/wct_test/test.log

Executed 1 out of 1 test: 1 fails locally.
jenkins@ec4d381ac7c1:/gerrit$ cat /home/jenkins/.cache/bazel/_bazel_jenkins/4198cff55ec080b15cc0805ba32b9d92/execroot/gerrit/bazel-out/local-fastbuild/testlogs/polygerrit-ui/app/wct_test/test.log
exec ${PAGER:-/usr/bin/less} "$0" || exit 1
-----------------------------------------------------------------------------
+ mktemp -d
+ t=/tmp/tmp.QQoMrSmy23
+ components=/home/jenkins/.cache/bazel/_bazel_jenkins/4198cff55ec080b15cc0805ba32b9d92/execroot/gerrit/bazel-out/local-fastbuild/bin/polygerrit-ui/app/wct_test.runfiles/gerrit/polygerrit-ui/app/test_components.zip
+ code=/home/jenkins/.cache/bazel/_bazel_jenkins/4198cff55ec080b15cc0805ba32b9d92/execroot/gerrit/bazel-out/local-fastbuild/bin/polygerrit-ui/app/wct_test.runfiles/gerrit/polygerrit-ui/app/pg_code.zip
+ echo /tmp/tmp.QQoMrSmy23
/tmp/tmp.QQoMrSmy23
+ unzip -qd /tmp/tmp.QQoMrSmy23 /home/jenkins/.cache/bazel/_bazel_jenkins/4198cff55ec080b15cc0805ba32b9d92/execroot/gerrit/bazel-out/local-fastbuild/bin/polygerrit-ui/app/wct_test.runfiles/gerrit/polygerrit-ui/app/test_components.zip
+ unzip -qd /tmp/tmp.QQoMrSmy23 /home/jenkins/.cache/bazel/_bazel_jenkins/4198cff55ec080b15cc0805ba32b9d92/execroot/gerrit/bazel-out/local-fastbuild/bin/polygerrit-ui/app/wct_test.runfiles/gerrit/polygerrit-ui/app/pg_code.zip
+ mkdir -p /tmp/tmp.QQoMrSmy23/test
+ cp /home/jenkins/.cache/bazel/_bazel_jenkins/4198cff55ec080b15cc0805ba32b9d92/execroot/gerrit/bazel-out/local-fastbuild/bin/polygerrit-ui/app/wct_test.runfiles/gerrit/polygerrit-ui/app/test/index.html /tmp/tmp.QQoMrSmy23/test/
+ cat
+ dirname /usr/bin/wct
+ dirname /usr/bin/npm
+ export PATH=/usr/bin:/usr/bin:.:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
+ cd /tmp/tmp.QQoMrSmy23
+ test -n /usr/bin/wct
+ basename /usr/bin/wct
+ wct
/usr/lib/node_modules/web-component-tester/node_modules/polyserve/lib/compile-middleware.js:126
    const [majorVersion, minorVersion] = versionSplit.map((v) => v ? parseInt(v, 10) : -1);
          ^

SyntaxError: Unexpected token [
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/lib/node_modules/web-component-tester/node_modules/polyserve/lib/start_server.js:34:30)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)

Patch-set: 7
Reviewer: Gerrit User 1029953 <1029953@173816e5-2b9a-37c3-8a2e-48639d4f1153>